<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.0</Version>
    <TargetFramework>net9.0-ios</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>
    <NoBindingEmbedding>true</NoBindingEmbedding>
    <IPhoneResourcePrefix>Resources</IPhoneResourcePrefix>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RepositoryUrl>https://github.com/Truvideo/truvideo-sdk-camera-net</RepositoryUrl>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CreatePackage>false</CreatePackage>
    <MtouchLink>None</MtouchLink>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CreatePackage>false</CreatePackage>
    <MtouchLink>SdkOnly</MtouchLink>
  </PropertyGroup>
  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
    <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
  </ItemGroup>
  <ItemGroup>
    <NativeReference Include="xcframeworks/TruvideoCamera.xcframework">
      <Kind>Framework</Kind>
      <SmartLink>False</SmartLink>
      <ForceLoad>True</ForceLoad>
      <Frameworks>Foundation UIKit AVFoundation CoreMedia</Frameworks>
      <LinkerFlags>-ObjC -lc++</LinkerFlags>
      <WeakFrameworks>SwiftUI</WeakFrameworks>
    </NativeReference>
    <NativeReference Include="xcframeworks/TruvideoSdkCamera.xcframework">
      <Kind>Framework</Kind>
      <SmartLink>False</SmartLink>
      <ForceLoad>True</ForceLoad>
      <Frameworks>Foundation UIKit AVFoundation CoreMedia</Frameworks>
      <LinkerFlags>-ObjC -lc++</LinkerFlags>
      <WeakFrameworks>SwiftUI</WeakFrameworks>
    </NativeReference>
  </ItemGroup>
</Project>
